name: 'coverage'

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Get Cover
        uses: orgoro/coverage@v3
        with:
          coverageFile: ./coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
