name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install libcurl4-openssl-dev libssl-dev
          python -m pip install --upgrade pip
          python -m pip install mkgendocs
          pip install .[all]
      - name: Generate Yml
        run: |
          python joatmon/generator/doc.py
      - name: Generate MD
        run: |
          gendocs --config mkgendocs.yml
