name: Docs

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          git checkout documentation
          git merge --strategy-option theirs master
          sudo apt install libcurl4-openssl-dev libssl-dev
          python -m pip install --upgrade pip
          python -m pip install mkgendocs
          pip install .[all]
      - name: Generate Docs
        run: |
          python joatmon/automate/generator/doc.py
      - name: Commit changes
        run: |
          git config --global user.email "hamitcanmalkoc@gmail.com"
          git config --global user.name "Hamitcan Malkoç"
          git add .
          git commit -m "release documentation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: false
