name: Pylint

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          python -m pylint --fail-under=10 --max-line-length=160 `find -regextype egrep -regex '(.*.py)$'` |
          tee pylint.txt
      - name: Upload pylint.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pylint report
          path: pylint.txt
