name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install libcurl4-openssl-dev libssl-dev
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest pytest-cov
          python -m pip install mkgendocs
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .[all]
      - name: Lint with flake8
        run: |
          pytest --cov-report term --cov=joatmon --cov-report xml:coverage.xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
